

octant_folder: "../cutouts/"


current_version: 230210

tech_years: [2020,2030,2040,2050]

tech_years_default: 2030

efuels:
  hydrogen_submarine_pipeline: Hydrogen by submarine pipeline
  methanol: Methanol by ship
  ammonia: Ammonia by ship
  electricity_hvdc: Electricity by submarine HVDC cable

efuels_default: hydrogen_submarine_pipeline

tech_data_commit: "3a23cfc5808df00a2c039fd0e7ce8755a090d4df"
trace_commit: "55e71c86d36869079b46377ce7ef16a46afa1d99"


years_available_start: 2011
years_available_end: 2012

float_upper_limit: 1.e+8

results_threshold: 1.e-3

#seconds
expected_time: 70

balances_to_display: ["electricity","hydrogen"]

preferred order: ["wind","solar","battery storage","battery inverter","hydrogen storage","hydrogen storing compressor","hydrogen electrolyser","hydrogen turbine"]

#LHV
mwh_per_t:
  hydrogen: 33
  methanol: 5.54
  ammonia: 5.17

#LHV at 20 C
mwh_per_m3:
  methanol: 4.4

colors:
  wind : "#3B6182"
  solar: "#FFFF00"
  battery: "#999999"
  battery_charge: "#999999"
  battery_discharge: "#999999"
  battery discharger: "#999999"
  battery_power: "#999999"
  battery inverter: "#999999"
  battery_energy: "#666666"
  battery storage: "#666666"
  hydrogen_turbine: red
  hydrogen turbine: red
  hydrogen_electrolyser: cyan
  hydrogen electrolyser: cyan
  hydrogen_energy: magenta
  hydrogen storage: magenta
  hydrogen storing compressor: "#ff66ff"
  hydrogen storing decompressor: "#660066"
  dispatchable1: orange
  dispatchable2: lime
  hydrogen_submarine_pipeline: green
  hydrogen submarine pipeline: green
  load: black
  efuels_load: purple
  hydrogen_load: purple
  methanol shipping: green
  methanol synthesis: "#F08080"
  methanol storage: black
  co2: "#708090"
  dac: "#708090"
  co2 storage: "#708090"
  heat pump: red
  hvdc: green
  ammonia storage: orange
  Haber-Bosch synthesis: brown
  air separation unit: red
  ammonia shipping: green
