

octant_folder: "../octants/"


current_version: 230210

weather_years: [2011,2012,2013,2014]

tech_years: [2020,2030,2040,2050]

tech_years_default: 2030

cost_year_assumptions: 2015
cost_year: 2020
inflation: 2

efuels:
  hydrogen_submarine_pipeline: hydrogen (gas) by submarine pipeline
  lh2: hydrogen (liquid) by ship
  ammonia: ammonia (liquid) by ship
  methane: methane (liquid) by ship
  methanol: methanol by ship
  ft: diesel/gasoline/kerosene by ship
  electricity_hvdc: electricity by submarine HVDC cable

efuels_default: hydrogen_submarine_pipeline

tech_data_commit: "3a23cfc5808df00a2c039fd0e7ce8755a090d4df"
trace_commit: "55e71c86d36869079b46377ce7ef16a46afa1d99"


float_upper_limit: 1.e+9

results_threshold: 1.e-3

#seconds
poll_interval: 1
poll_timeout: 600
expected_time: 120

balances_to_display: ["electricity","hydrogen"]

preferred order: ["wind","solar","battery storage","battery inverter","hydrogen storage","hydrogen storing compressor","hydrogen electrolyser","seawater desalination","hydrogen turbine"]

#steel tank in bar
methane storage pressure: 80

#LHV
mwh_per_t:
  hydrogen: 33.3
  lh2: 33.3
  methanol: 5.54
  ammonia: 5.17
  methane: 13.9
  ft: 11.95

#LHV at 20 C
mwh_per_m3:
  methanol: 4.4
  methane: 0.01
  ft: 9.92

colors:
  wind : "#3B6182"
  solar: "#FFFF00"
  battery: "#999999"
  battery_charge: "#999999"
  battery_discharge: "#999999"
  battery discharger: "#999999"
  battery_power: "#999999"
  battery inverter: "#999999"
  battery_energy: "#666666"
  battery storage: "#666666"
  hydrogen_turbine: red
  hydrogen turbine: red
  hydrogen_electrolyser: cyan
  hydrogen electrolyser: cyan
  hydrogen_energy: magenta
  hydrogen storage: magenta
  hydrogen storing compressor: "#ff66ff"
  hydrogen storing decompressor: "#660066"
  hydrogen liquefaction: "#cc3300"
  lh2 shipping: green
  dispatchable1: orange
  dispatchable2: lime
  hydrogen_submarine_pipeline: green
  hydrogen submarine pipeline: green
  load: black
  efuels_load: purple
  hydrogen_load: purple
  methanol shipping: green
  methanol synthesis: "#F08080"
  methanol storage: black
  methane shipping: green
  methanation: "#F08080"
  methane liquefaction: "#cc3300"
  methane storage: black
  ft synthesis: "#F08080"
  ft storage: black
  ft shipping: green
  co2: "#999966"
  dac: "#999966"
  co2 storage: "#666633"
  heat pump: red
  hvdc: green
  ammonia storage: orange
  Haber-Bosch synthesis: brown
  air separation unit: red
  ammonia shipping: green
  seawater desalination: "#000099"
